#!/usr/bin/env python3
"""
build_roster.py  ·  IPMAT Arena roster pipeline
------------------------------------------------
Ingest an IMS masterdata .xlsx and produce a clean login roster.

This is ALSO the re-upload processor: whenever new students enrol, drop the new
masterdata file in and re-run. It regenerates roster.sql, which you apply to the
D1 database to refresh who can log in.

Login model it feeds:  student types IMS PIN -> backend looks it up here ->
match unlocks and returns {name, batch}; no match = no login. Batch is fetched,
never chosen.

Outputs (in ../build, git-ignored because they contain student PII):
  roster.json    PIN -> {name, batch}   (for reference / local dev)
  roster.sql     TRUNCATE + INSERTs for the Cloudflare D1 `students` table
  roster_report.txt  aggregate report (NO PINs / PII) — safe to share

Usage:
  python3 build_roster.py "/path/to/Masterdata.xlsx"
"""
import sys, json, re, os
from pathlib import Path
import pandas as pd

# ------------------------------------------------------------------ config ----
# Who counts as an Ahmedabad IPMAT student. Edit these to change the roster.
KEEP_STATUS   = {"active"}
REQUIRE_IN_VARIANT = "ipm"          # variant must contain this (IPMAT programs)
EXCLUDE_VARIANT_ANY = ["law", "clat", "gdpi", " ug", "ug2"]  # never IPMAT-QA
EXCLUDE_BATCH_ANY   = ["law", "clat", "gdpi", "ug"]          # safety net on batch code

# Batch-code families treated as Ahmedabad IPMAT. A batch is INCLUDED if it
# matches one of these regexes (case-insensitive) and isn't excluded above.
AHMEDABAD_BATCH_PATTERNS = [
    r"^A-?\d{3,4}$",     # A-2711, A2711, A-2805 ...
    r"^A27-[A-Z]$",      # A27-A .. A27-E
    r"^Z\d{3,4}$",       # Z2701, Z2801  (Zebar)
    r"^S\d{3,4}$",       # S2801
    r"^PN\d{3,4}$",      # PN2801
    r"^ZEBAR$",
    # 26/27-MGMT + E-batches EXCLUDED per JJ (2026-09-21) — another center/program.
    # To re-include, add:  r"^26\s*MGMT",  r"^27\s*MGMT",  r"^IPM\s*27",
]
# --------------------------------------------------------------------------- --

HERE = Path(__file__).resolve().parent
BUILD = HERE.parent / "build"
BUILD.mkdir(exist_ok=True)

def norm_batch(v):
    if pd.isna(v): return ""
    return re.sub(r"\s+", " ", str(v).strip()).upper()

def is_ahmedabad(batch):
    b = batch.upper()
    if any(x in b.lower() for x in EXCLUDE_BATCH_ANY): return False
    return any(re.match(p, b) for p in AHMEDABAD_BATCH_PATTERNS)

def sql_str(s): return "'" + str(s).replace("'", "''") + "'"

def main(path):
    df = pd.read_excel(path)
    df.columns = [c.strip() for c in df.columns]
    total = len(df)

    df["_status"]  = df["STATUS"].astype(str).str.strip().str.lower()
    df["_variant"] = df["Variant"].astype(str).str.lower()
    df["_pin"]     = df["IMS PIN"].astype(str).str.strip()
    df["_batch"]   = df["Current Batch"].apply(norm_batch)
    df["_first"]   = df["First Name"].astype(str).str.strip().replace("nan", "")
    df["_last"]    = df["Last Name"].astype(str).str.strip().replace("nan", "")
    df["_name"]    = (df["_first"] + " " + df["_last"]).str.strip()

    # ---- filter funnel ----
    active = df[df["_status"].isin(KEEP_STATUS)]
    ipm = active[active["_variant"].str.contains(REQUIRE_IN_VARIANT, na=False)
                 & ~active["_variant"].apply(lambda v: any(x in v for x in EXCLUDE_VARIANT_ANY))]

    has_pin  = ipm[ipm["_pin"].str.len() >= 6]
    has_name = has_pin[has_pin["_name"].str.len() > 0]

    kept, dropped_batch, blank_batch = [], {}, 0
    for _, r in has_name.iterrows():
        b = r["_batch"]
        if b == "":
            blank_batch += 1; continue
        if is_ahmedabad(b):
            kept.append(r)
        else:
            dropped_batch[b] = dropped_batch.get(b, 0) + 1

    kdf = pd.DataFrame(kept)

    # ---- de-duplicate PINs ----
    seen, conflicts, roster = {}, [], {}
    for _, r in kdf.iterrows():
        pin, name, batch = r["_pin"], r["_name"], r["_batch"]
        if pin in seen:
            if seen[pin][0].lower() != name.lower():
                conflicts.append((pin, seen[pin], (name, batch)))
            continue
        seen[pin] = (name, batch)
        roster[pin] = {"name": name, "batch": batch}

    # ---- write roster.json ----
    (BUILD / "roster.json").write_text(json.dumps(roster, indent=0, ensure_ascii=False))

    # ---- write roster.sql (for Cloudflare D1) ----
    lines = ["-- Generated by build_roster.py — refreshes the login roster.",
             "DELETE FROM students;"]
    for pin, rec in roster.items():
        lines.append(f"INSERT INTO students (pin, name, batch) VALUES "
                     f"({sql_str(pin)}, {sql_str(rec['name'])}, {sql_str(rec['batch'])});")
    (BUILD / "roster.sql").write_text("\n".join(lines) + "\n")

    # ---- batch breakdown of the kept roster ----
    fam = {}
    for rec in roster.values():
        fam[rec["batch"]] = fam.get(rec["batch"], 0) + 1

    def family_of(b):
        if re.match(r"^A-?\d", b): return "A-series (Ahmedabad classroom)"
        if re.match(r"^A27-", b):  return "A27-x (Ahmedabad)"
        if b.startswith("Z"):      return "Z-series (Zebar)"
        if b.startswith("S"):      return "S-series"
        if b.startswith("PN"):     return "PN-series"
        if "MGMT" in b or b.startswith("IPM 27"): return "26/27-MGMT + E-batches (CONFIRM)"
        return "other"
    fam_group = {}
    for b, n in fam.items():
        g = family_of(b); fam_group.setdefault(g, [0, 0]); fam_group[g][0]+=n; fam_group[g][1]+=1

    # ---- report (NO PINs) ----
    R = []
    R.append("IPMAT ARENA — ROSTER BUILD REPORT")
    R.append("="*44)
    R.append(f"Source rows in file ............ {total}")
    R.append(f"Active ......................... {len(active)}")
    R.append(f"Active + IPMAT variant ......... {len(ipm)}")
    R.append(f"  with a valid PIN ............. {len(has_pin)}")
    R.append(f"  with a name .................. {len(has_name)}")
    R.append(f"Blank batch (dropped) .......... {blank_batch}")
    R.append(f"Non-Ahmedabad batch (dropped) .. {sum(dropped_batch.values())}")
    R.append("")
    R.append(f"==> ROSTER SIZE (can log in) ... {len(roster)}  across {len(fam)} batches")
    R.append("")
    R.append("Included by family:")
    for g,(n,c) in sorted(fam_group.items(), key=lambda x:-x[1][0]):
        R.append(f"   {n:5d} students  ·  {c:2d} batches  ·  {g}")
    R.append("")
    R.append("DUPLICATE PINs:")
    R.append(f"   {len(conflicts)} PIN(s) map to a DIFFERENT name (true conflicts — fix in masterdata).")
    if conflicts:
        R.append("   (PINs masked; full list in build/pin_conflicts.txt)")
    R.append("")
    R.append("Dropped non-Ahmedabad / non-IPMAT batches:")
    for b,n in sorted(dropped_batch.items(), key=lambda x:-x[1]):
        R.append(f"   {n:4d}  {b}")
    report = "\n".join(R)
    (BUILD / "roster_report.txt").write_text(report + "\n")

    # conflicts file (has PINs -> local only)
    if conflicts:
        cl = ["PIN\tkept_name\tkept_batch\tconflicting_name\tconflicting_batch"]
        for pin, a, b in conflicts:
            cl.append(f"{pin}\t{a[0]}\t{a[1]}\t{b[0]}\t{b[1]}")
        (BUILD / "pin_conflicts.txt").write_text("\n".join(cl) + "\n")

    print(report)
    print("\nWrote: build/roster.json  build/roster.sql  build/roster_report.txt"
          + ("  build/pin_conflicts.txt" if conflicts else ""))

if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else str(Path.home()/"Downloads"/"Masterdata-only (2).xlsx")
    main(src)
